auto: false
server: false
markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
permalink: /:year/:month/:title/
pygments: true
name: TACplan
description: Military Grade Solutions
url: http://www.tacplan.com
provider: google
google_analytics_id: UA-39122819-1