auto: false
server: false
markdown: rdiscount
extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: /:year/:month/:title/
pygments: true
name: TACplan
description: Military Grade Solutions
url: http://www.tacplan.com